# Generated by Django 4.2.4 on 2023-08-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.IntegerField()),
                ('vname', models.CharField(max_length=40)),
                ('vemail', models.EmailField(max_length=30)),
            ],
        ),
    ]
