# Generated by Django 4.2.7 on 2023-11-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='userpic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
