# Generated by Django 4.2.7 on 2023-11-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_donation_donationpic_alter_gallery_deliverypic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donationpic',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
