# Generated by Django 4.2.7 on 2023-11-07 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_alter_donor_user_alter_volunteer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donationarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.donationarea'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.volunteer'),
        ),
    ]
